# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GalleryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryApp
  pod 'Conv'
  pod 'Blueprints'
  pod 'TRMosaicLayout'
  pod "FMMosaicLayout"
  pod 'M13Checkbox'
  pod 'Then'
  pod 'CheckMarkView'
end
